
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace KeremBilirProje.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Question
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Question()
    {

        this.Answer = new HashSet<Answer>();

    }


    public string qId { get; set; }

    public string qTitle { get; set; }

    public string qBody { get; set; }

    public string qUserId { get; set; }

    public string qCatId { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Answer> Answer { get; set; }

    public virtual Category Category { get; set; }

    public virtual User User { get; set; }

}

}
